name: quantum_env_2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26
  - scipy
  - matplotlib
  - qutip
  - numba
  - statsmodels
  - pip
  - pip:
      - qiskit
      - qiskit-aer
      - qiskit-ibm-runtime
      - quspin
